version: '3.8'

services:
  # Development Backend
  backend-dev:
    build:
      context: ./backend
      target: development
    container_name: medical-chatbot-api-dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
      - /app/__pycache__
    restart: unless-stopped
    networks:
      - medical-chatbot-dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]

  # Development Frontend
  frontend-dev:
    build:
      context: ./frontend
      target: dependencies
    container_name: medical-chatbot-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      - /app/.next
      - /app/node_modules
    restart: unless-stopped
    networks:
      - medical-chatbot-dev
    depends_on:
      - backend-dev
    command: ["npm", "run", "dev"]

networks:
  medical-chatbot-dev:
    driver: bridge
    name: medical-chatbot-dev
